# Generated by Django 3.0.7 on 2021-09-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('data_id', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('download_data_status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
                ('company', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
