# Generated by Django 3.0.7 on 2021-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210908_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='file_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
